apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collage.fullname" . }}-secret

type: Opaque

stringData:
  DB_USER: {{ .Values.mysql.user | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | quote }}
